{% set name = "pip-tools" %}
{% set version = "6.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pip-tools-{{ version }}.tar.gz
  sha256: 06366be0e08d86b416407333e998b4d305d5bd925151b08942ed149380ba3e47

build:
  number: 0
  noarch: python
  entry_points:
    - pip-compile = piptools.scripts.compile:cli
    - pip-sync = piptools.scripts.sync:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - setuptools-scm
    - pip
  run:
    - python >=3.7
    - python-build
    - click >=7
    - pip >=21.2
    - setuptools
    - wheel

test:
  imports:
    - piptools
  commands:
    - pip check
    - pip-compile --help
    - pip-sync --help
  requires:
    - pip

about:
  home: https://pypi.org/project/pip-tools/
  summary: pip-tools keeps your pinned dependencies fresh.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
