{% set name = "pip-tools" %}
{% set version = "5.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be6190405e4206526607aa4813bd6d7a949e4fdc180d0db4f3221f3778846cf7

build:
  number: 0
  noarch: python
  entry_points:
    - pip-compile = piptools.scripts.compile:cli
    - pip-sync = piptools.scripts.sync:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
    - setuptools_scm
  run:
    - click >=7
    - pip >=20.0
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4
    - six

test:
  imports:
    - piptools
    - piptools._compat
  commands:
    - pip check
    - pip-compile --help
    - pip-sync --help
  requires:
    - pip

about:
  home: https://pypi.org/project/pip-tools/
  summary: pip-tools keeps your pinned dependencies fresh.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
