{% set name = "pip-tools" %}
{% set version = "6.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f638503a9f77d98d9a7d72584b1508d3f82ed019b8fab24f4e5ad078c1b8c95e

build:
  number: 0
  noarch: python
  entry_points:
    - pip-compile = piptools.scripts.compile:cli
    - pip-sync = piptools.scripts.sync:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - click >=7
    - pep517
    - pip >=20.3
    - python >=3.6

test:
  imports:
    - piptools
  commands:
    - pip check
    - pip-compile --help
    - pip-sync --help
  requires:
    - pip

about:
  home: https://pypi.org/project/pip-tools/
  summary: pip-tools keeps your pinned dependencies fresh.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
