{% set name = "pip-tools" %}
{% set version = "7.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pip-tools-{{ version }}.tar.gz
  sha256: 8e9c99127fe024c025b46a0b2d15c7bd47f18f33226cf7330d35493663fc1d1d

build:
  number: 0
  skip: True  # [py<37]
  entry_points:
    - pip-compile = piptools.scripts.compile:cli
    - pip-sync = piptools.scripts.sync:cli
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv

requirements:
  host:
    - python
    - setuptools-scm
    - setuptools
    - pip
    - wheel
  run:
    - python
    - python-build
    - click >=8
    - pip >=22.2
    - setuptools
    - wheel
    - tomli  # [py<311]

test:
  source_files:
    - tests
  imports:
    - piptools
  commands:
    - pip check
    - pip-compile --help
    - pip-sync --help
    # Fix locale settings on osx
    - export LANGUAGE=en_US.UTF-8 # [osx]
    - export LC_ALL=en_US.UTF-8 # [osx]
    - export LANG=en_US.UTF-8 # [osx]
    - export LC_CTYPE=en_US.UTF-8 # [osx]
    - pytest -vv tests -k "not (test_combine_different_extras_of_the_same_package or test_pass_pip_cache_to_pip_args or test_read_cache_permission_error)" -m 'not network'  # [linux]

    
    
  requires:
    - pip
    - pytest
    - tomli-w
    - pytest-xdist
    - pytest-rerunfailures
    - flit-core >=2,<4
    - poetry-core >=1.0.0
    - git  # [not win]

about:
  home: https://pypi.org/project/pip-tools/
  summary: pip-tools keeps your pinned dependencies fresh.
  license_family: BSD
  license: BSD-3-Clause
  license_file: LICENSE
  description: A set of command line tools to help you keep your pip-based packages fresh, even when you've pinned them.
  doc_url: https://pip-tools.readthedocs.io/en/
  dev_url: https://github.com/jazzband/pip-tools

extra:
  recipe-maintainers:
    - marcelotrevisani
